#!/bin/sh
if status is-interactive
  set fish_greeting "Welcome, wanderer of shadows, to the depths of the void..."
	# general
	alias die="sudo shutdown -h now"
	alias cp='cp -iv'
	alias mv='mv -iv'      
	alias wget='wget -c'
	alias rm='rm -v'       
	alias yeet='rm -rf'
  alias yeeet='sudo rm -rf'
	alias mkdir='mkdir -pv'
	alias ls='ls -hN --color=auto --group-directories-first'
	alias lsa='ls -a -hN --color=auto --group-directories-first'
	alias ls-storage="du -hsx -- * | sort -rh | head -10"
	alias compress='tar -czvf'
	alias extract='tar -xzvf'
  alias update-grub='sudo update-grub'

	# alternatives
	alias vi='nvim'
	alias vim='nvim'
	alias nano='nvim'
  alias nnvim='sudo nvim'
	alias code='code-oss'

	# utilities
	alias myip='curl ipinfo.io/ip'
  alias oc='~/stuff/scripts/code.sh'

	# networkmanager
	alias nmtui='sudo nmtui'

	# xbps
	alias i='sudo xbps-install -S'
	alias update='i; sudo xbps-install -u xbps; sudo xbps-install -u'
	alias remove='sudo xbps-remove -R'
  alias removeo='sudo xbps-remove -o'
	alias search='sudo xbps-query -Rs'
	alias searchl='sudo xbps-query -l'
		
	# youtube-dl
	alias get-audio='youtube-dl --extract-audio -f bestaudio '
	alias get-video='youtube-dl -f bestvideo+bestaudio '
	
	# pacman
	alias pac-unlock='sudo rm /var/lib/pacman/db.lck'
	alias pac-clean='sudo pacman -Rns (pacman -Qtdq)'
	
	# paths
  alias fishc="cd ~/.config/fish && nvim config.fish"
	alias bmwc='cd ~/stuff/code/dwm && nvim config.h'
	alias bmwp='cd ~/stuff/code/dwm && nvim patches.h'

	alias slc='cd ~/stuff/code/slstatus && nvim config.h'
	alias slp='cd ~/sutff/code/slstatus && nvim patches.h'

	alias dmenuc='cd ~/stuff/code/dmenu && nvim config.h'
	alias dmenup='cd ~/stuff/code/dmenu &&  nvim patches.h'

	alias stc='cd ~/stuff/code/st && nvim config.h'
	alias stp='cd ~/stuff/code/st && nvim patches.h'

  alias slockc='cd ~/stuff/code/slock && nvim config.h'
  alias slockp='cd ~/stuff/code/slock && nvim patches.h'

	alias theme='nvim ~/stuff/noties/dracula.lua'

	alias codexyz='code ~/stuff/code/khaledwaleed.xyz && exit'
  alias codemob='code ~/stuff/code/mob-website && exit'
  
  alias codef='cd ~/stuff/code/'

  alias sc='nvim ~/.config/sxhkd/sxhkdrc'

	# funny
	alias reyeet='sudo reboot'
	alias gimme='sudo xbps-install -S'
	alias obey='sudo'
	alias obey_as_me='sudo -E'
	alias say='yes'
	alias weather='curl wttr.in'
	alias toottoot='sl'
  alias sl='sl -100wdae'
	alias yeetermeter='btop'
	alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'



  export NNN_PLUG='h:finder;o:fzopen;p:mocq;d:diffs;t:nmount;v:imgview'
  export NNN_FIFO=/tmp/nnn.fifo

#
#   jump shell fish | source
#
# The following lines are autogenerated:

function __jump_add --on-variable PWD
  status --is-command-substitution; and return
  jump chdir
end

function __jump_hint
  set -l term (string replace -r '^j ' '' -- (commandline -cp))
  jump hint "$term"
end

function j
  set -l dir (jump cd "$argv")
  test -d "$dir"; and cd "$dir"
end

complete --command j --exclusive --arguments '(__jump_hint)'

end
